name: Automerge PR

on:
  pull_request_review:
    types: [submitted]
    
env:
  GH_TOKEN: ${{ github.token }}

jobs:
  approved:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    steps:
      - name: Check Approval
        run: echo "This PR was approved"

      - name: Get PR number
        run: |
          gh pr list | grep "${{ github.context.head.ref }}" | awk '{print $1}'
          outputs:
            pr_number: ${{ steps.get_pr_number.outputs.PR_NUMBER }}

      - name: Add labels
        run: |
          gh pr label ${{ steps.get_pr_number.outputs.pr_number }} correct-pr best
      
