name: Auto Label PR

on:
  pull_request_review:
    types: [submitted]

jobs:
  auto-label:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            console.log(github);
            
            github.issues.addLabels({
              issue_number: context.issue.number,
              labels: ['approved']
            })
