name: Auto Label PR

on:
  pull_request_target

jobs:
  auto-label:
    permissions:
        contents: read
        pull-requests: write
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    steps:
      - name: Check Approval
        run: echo "This PR was approved"

      - name: Add labels
        uses: actions/labeler@v4
        with:
          configuration_path: .github/labeler.yml
