name: Automerge PR

on:
  pull_request_review:
    types: [submitted, updated]

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Install gh
        run: |
          npm install -g gh

      - name: Print pull request number
        run: |
          gh pr number

      # - name: Add label
      #   run: |
      #     gh pr label ${github.context.payload.pull_request.number} correct-pr best
