name: Automerge PR

on:
  pull_request_review:
    types: [submitted, updated]

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Get approval status
        id: get_approval_status
        run: |
          echo "::set-output name=APPROVAL_STATUS::${{ github.context.payload.pull_request.review.state }}"

      - name: Print pull request number
        run: |
          echo "${{ github.context.payload.pull_request.number }}"

      - name: Add label
        run: |
          gh pr label ${github.context.payload.pull_request.number} correct-pr best
