name: Automerge PR

on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    steps:
      - name: Check Approval
        run: echo "This PR was approved"

      - name: Add labels
        run: |
          gh pr label ${{ github.context.payload.pull_request.number }} correct-pr best
      
